apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: defectdojo-secrets
  namespace: defectdojo
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: defectdojo-secrets
    type: Opaque

  data:
  - remoteRef:
      key: defectdojo
      property: django-secret-key
    secretKey: DD_SECRET_KEY
  - remoteRef:
      key: defectdojo
      property: database-password
    secretKey: DD_DATABASE_PASSWORD
  - remoteRef:
      key: defectdojo
      property: redis-password
    secretKey: DD_REDIS_PASSWORD
  - remoteRef:
      key: defectdojo
      property: admin-password
    secretKey: DD_ADMIN_PASSWORD
  - remoteRef:
      key: defectdojo
      property: credential-aes-key
    secretKey: DD_CREDENTIAL_AES_256_KEY
  - remoteRef:
      key: defectdojo
      property: metrics-auth-password
    secretKey: METRICS_HTTP_AUTH_PASSWORD