# External Secret for Redis-specific authentication
# Some DefectDojo components expect this specific secret format
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: defectdojo-redis-secret
  namespace: defectdojo
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: defectdojo-redis-specific
    type: Opaque

  data:
  - remoteRef:
      key: defectdojo
      property: redis-password
    secretKey: redis-password