apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fetdevops-cert
  namespace: istio-ingress
spec:
  secretName: fetdevops-tls-cert
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: online.fetdevops.com
  dnsNames:
  - online.fetdevops.com
  - grafana.fetdevops.com
  - argocd.fetdevops.com
  - defectdojo.fetdevops.com