apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-authorization-policy.yaml
  - defectdojo-authorization-policy.yaml
  - frontend-authorization-policy.yaml
  - gateway.yaml
  - online-boutique-peer-authentication.yaml