apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: service
          image: checkoutservice-image
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: EMAIL_SERVICE_ADDR
              value: emailservice:5000
            - name: PAYMENT_SERVICE_ADDR
              value: paymentservice:50051
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 64m
              memory: 64Mi
          livenessProbe:
            grpc:
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            grpc:
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: checkoutservice
  type: ClusterIP