apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: service
          image: frontend-image
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: RECOMMENDATION_SERVICE_ADDR
              value: recommendationservice:8080
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: CHECKOUT_SERVICE_ADDR
              value: checkoutservice:5050
            - name: AD_SERVICE_ADDR
              value: adservice:9555
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              value: "shoppingassistantservice:80"
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 64m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /_healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: frontend-proxy
#  annotations:
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/target-type: ip
#    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:495599766789:certificate/52b92fd1-5029-4cc8-bc32-d050f1e3ef3e
#  labels:
#    name: frontend-proxy
#spec:
#  ingressClassName: alb
#  tls:
#    - hosts:
#        - shop.fetdevops.com
#      secretName: dummy-placeholder # Required field, even if ALB ignores it
#  rules:
#    - host: shop.fetdevops.com
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/"
#            backend:
#              service:
#                name: frontend
#                port:
#                  number: 80