apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-boutique-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: online-boutique
  namespaceSelector:
    matchNames:
      - online-boutique
  endpoints:
    - port: http
      interval: 30s
      path: /metrics